#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 5114 rows and 979 variables:
#' \describe{
#'   \item{\code{RACE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ETHNICITY}}{double COLUMN_DESCRIPTION}
#'   \item{\code{h4od1y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{iyear4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{AID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{BIO_SEX}}{double COLUMN_DESCRIPTION}
#'   \item{\code{agew1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{IMONTH4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{IDAY4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{MACNO4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{INTID4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{BIO_SEX4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{VERSION4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{BREAK_Q}}{character COLUMN_DESCRIPTION}
#'   \item{\code{PRYEAR4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PRETEST4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PRISON4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD1M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD2C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD2D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD2E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD2F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD6M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD6Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4OD7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP2M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP2Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP8M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP8Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP15M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP15Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP29M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP29Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP32}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP33}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP34}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP35}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP36}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP37}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP38}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP39}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WP40}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS3H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WS5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH3M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH3D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH3Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH5F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH5I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH11H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH11M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH11T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH13H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH13M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4GH13T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS2C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS2D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HS9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID5N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID6N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID9C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID9D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID9E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID9F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID9G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID10H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ID26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP1H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP1M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP1T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP2H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP2M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP2T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP3H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP3M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP3T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP4H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP4M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP4T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SP7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR5P}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR6P}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR7P}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR8P}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR9P}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MB}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YB}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MD}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YD}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11ME}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MF}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YF}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MG}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YG}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MH}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YH}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MI}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YI}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MJ}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YJ}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MK}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YK}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11ML}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YL}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MM}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YM}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MN}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YN}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11MO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HR11YO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED3H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED4H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED5H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ED9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI4C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI4D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI4E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI6C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI8M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI8Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI9M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI9Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI11Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI11M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI12Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI12M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI16A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI16B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI16C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI16D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MI17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM8}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H4LM9M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM9Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM15M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM15Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM16M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM16Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM18}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H4LM19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM21A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM21B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM21C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4LM30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EC19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RE11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C4WD90_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C4WD90_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C4WD90_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C4WD60_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C4WD60_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C4WD60_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH11A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH11B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH12A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH12B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH13A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH13B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH14A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH14B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH15B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH16A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH16B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH17A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH17B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C4NUMSCR}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MH29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26P}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26Q}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26R}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26S}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26U}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE26V}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE32}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE33}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE34}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE35}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE36O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37L}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37N}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SE37O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TR12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PTNR_ID}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD2D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD2M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD2Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD7C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD7D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD7E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD7F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD7G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD14T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4RD25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4KK14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4KK15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4KK15B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4KK15C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4KK15D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DS20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ7K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ9K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ13K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ15K}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ22Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ22M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ23Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ23M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ24Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ24M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ25Y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CJ25M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO32H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO32M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO32T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO33}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO34}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO35}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO36}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO37}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO38}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO39}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO40}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO41}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO42H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO42M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO42T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO43}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO44}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO45}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO46}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO47}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO48}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO49}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO50}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO51}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO52}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO53}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO54}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO55}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO56}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO57}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO58}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO59}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO60}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO61}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO62}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO63}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO64A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO64B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO64C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO64D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO65A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO65B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO65C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO65D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO65E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO66}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO67}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO68}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO69}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO70}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO71}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO72}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO73H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO73M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO73T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO74}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO75}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO76}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO77}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO78}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO79}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO80}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO81}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO82}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO83}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO84}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO85}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO86}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO87}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO88}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO89}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO90}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO91}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO92}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO93}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO94}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO95}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO96}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO97}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO100}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO101H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO101M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO101T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO102}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO103}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO104}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO105}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO106}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO107}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO108}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO109}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO110}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO111}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO112}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO113}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO114}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO115}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO116}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO117}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO118}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO119}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4TO120}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MA1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MA2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MA3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MA4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MA5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MA6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA12H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA12M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA12T}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA15B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA15C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA15D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA15E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DA28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE32}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE33}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE34}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE35}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE36}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE37}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE38}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE39}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE40}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PE41}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CMONTH}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CDAY}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CYEAR}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4ARM}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CUFF}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4CUFFLG}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4SBP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4DBP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4BPCLS}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4BPFLG}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PR}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4PP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4MAP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4HGT}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WGT}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WTLBS}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4BMI}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4BMICLS}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4WAIST}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4IR16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5G}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5H}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5I}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO5J}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4EO7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{AGE4}}{double COLUMN_DESCRIPTION} 
#'}
#' @details DETAILS
NULL